name: Testing - Reusable Workflow
on: 
  workflow_call:
    inputs:
      ingress-url:
          description: Provide the Ingress URL
          required: true
          type: string
jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - env:
          URL: ${{ inputs.ingress-url }}
        run: |
          curl https://$URL/live -s -k | jq -r .status | grep -i live
  dev-deploy:
    needs: docker
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-kubectl@v4
        with:
          version: v1.28.1
      - uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: '${{ secrets.KUBECONFIG }}'
      - run: kubectl version -o yaml
